name: Continuous Integration

on:
  pull_request: null
  push:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-33-jdk17
    steps:
      - uses: actions/checkout@v3
      - name: Run detekt
        run: ./gradlew detekt
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif